# build stage
FROM golang:1.26-alpine AS build-env
RUN apk add make git bash build-base
ENV GOPATH=/go
ENV PATH="/go/bin:${PATH}"

WORKDIR /go/src/github.com/ohsu-comp-bio/funnel
COPY go.* ./
RUN go mod download
COPY . ./
RUN apk add --no-cache bash build-base git protobuf protobuf-dev
RUN make build

# final stage
FROM alpine

RUN apk add --no-cache docker-cli

WORKDIR /opt/funnel
EXPOSE 8000 9090
ENV PATH="/app:${PATH}"

COPY --from=build-env /go/src/github.com/ohsu-comp-bio/funnel/funnel /app/

ENTRYPOINT ["/app/funnel"]
