# Start from the official Funnel image
FROM quay.io/ohsu-comp-bio/funnel:latest

# Switch to root to overwrite the system binaries
USER root

# Download and extract the modern static Docker CLI (v26.0.0 / API 1.45)
RUN wget -qO- https://download.docker.com/linux/static/stable/x86_64/docker-26.0.0.tgz | tar xvz && \
    mv docker/docker /usr/local/bin/docker && \
    rm -rf docker

# Funnel's default entrypoint will now use the modern CLI when it shells out!