apiVersion: v1
kind: ConfigMap
metadata:
  name: funnel-config-central
  namespace: fl-system
data:
  funnel.config.yaml: |
    Server:
      HostName: "0.0.0.0"
      HTTPPort: "8000"
      RPCPort: "9090"
    Compute: local
    BoltDB:
      Path: /tmp/funnel/central/db/funnel.db
    Worker:
      WorkDir: /tmp/funnel/central/work-dir
    LocalStorage:
      AllowedDirs:
        - /tmp/funnel/central/work-dir
        - /tmp
        - /workspace
        - /data
        - .
        - ./shared_workspace/
    GenericS3:
      - Disabled: false
        Endpoint: "http://minio.fl-system.svc.cluster.local:9000"
        Key: "minioadmin"
        Secret: "minioadmin"
    AmazonS3:
      Disabled: true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: funnel-config-site-1
  namespace: fl-system
data:
  funnel.config.yaml: |
    Server:
      HostName: "0.0.0.0"
      HTTPPort: "8000"
      RPCPort: "9090"
    Compute: local
    BoltDB:
      Path: /tmp/funnel/site-1/db/funnel.db
    Worker:
      WorkDir: /tmp/funnel/site-1/work-dir
    LocalStorage:
      AllowedDirs:
        - /tmp/funnel/site-1/work-dir
        - /tmp
        - /workspace
        - /data
        - .
        - ./shared_workspace/
    GenericS3:
      - Disabled: false
        Endpoint: "http://minio.fl-system.svc.cluster.local:9000"
        Key: "minioadmin"
        Secret: "minioadmin"
    AmazonS3:
      Disabled: true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: funnel-config-site-2
  namespace: fl-system
data:
  funnel.config.yaml: |
    Server:
      HostName: "0.0.0.0"
      HTTPPort: "8000"
      RPCPort: "9090"
    Compute: local
    BoltDB:
      Path: /tmp/funnel/site-2/db/funnel.db
    Worker:
      WorkDir: /tmp/funnel/site-2/work-dir
    LocalStorage:
      AllowedDirs:
        - /tmp/funnel/site-2/work-dir
        - /tmp
        - /workspace
        - /data
        - .
        - ./shared_workspace/
    GenericS3:
      - Disabled: false
        Endpoint: "http://minio.fl-system.svc.cluster.local:9000"
        Key: "minioadmin"
        Secret: "minioadmin"
    AmazonS3:
      Disabled: true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: funnel-config-site-3
  namespace: fl-system
data:
  funnel.config.yaml: |
    Server:
      HostName: "0.0.0.0"
      HTTPPort: "8000"
      RPCPort: "9090"
    Compute: local
    BoltDB:
      Path: /tmp/funnel/site-3/db/funnel.db
    Worker:
      WorkDir: /tmp/funnel/site-3/work-dir
    LocalStorage:
      AllowedDirs:
        - /tmp/funnel/site-3/work-dir
        - /tmp
        - /workspace
        - /data
        - .
        - ./shared_workspace/
    GenericS3:
      - Disabled: false
        Endpoint: "http://minio.fl-system.svc.cluster.local:9000"
        Key: "minioadmin"
        Secret: "minioadmin"
    AmazonS3:
      Disabled: true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: funnel-config-site-4
  namespace: fl-system
data:
  funnel.config.yaml: |
    Server:
      HostName: "0.0.0.0"
      HTTPPort: "8000"
      RPCPort: "9090"
    Compute: local
    BoltDB:
      Path: /tmp/funnel/site-4/db/funnel.db
    Worker:
      WorkDir: /tmp/funnel/site-4/work-dir
    LocalStorage:
      AllowedDirs:
        - /tmp/funnel/site-4/work-dir
        - /tmp
        - /workspace
        - /data
        - .
        - ./shared_workspace/
    GenericS3:
      - Disabled: false
        Endpoint: "http://minio.fl-system.svc.cluster.local:9000"
        Key: "minioadmin"
        Secret: "minioadmin"
    AmazonS3:
      Disabled: true