Server:
  HostName: localhost
  HTTPPort: '8000'
LocalStorage:
  AllowedDirs:
  - /tmp/tes-workspace
  - /tmp
  - /workspace
  - /data
  - .
  - ./shared_workspace/
  - /home/viditkh/GSoC/trustworthy_federated_ai/shared_workspace/checkpoints/
Compute: local

GenericS3:
  - Disabled: true

AmazonS3:
  Disabled: false
Worker:
  WorkDir: /opt/funnel/central/work-dir

BoltDB:
  Path: /opt/funnel/central/db/funnel.db