Server:
  HostName: localhost
  HTTPPort: '8000'
LocalStorage:
  AllowedDirs:
  - /tmp/tes-workspace
  - /tmp
  - /workspace
  - /data
  - .
  - ./shared_workspace/

Compute: local

GenericS3:
  - Disabled: true

AmazonS3:
  Disabled: false
Worker:
  WorkDir: /opt/funnel/site-d/work-dir

BoltDB:
  Path: /opt/funnel/site-d/db/funnel.db